apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGEwcGtlZGky
  CLOUDINARY_KEY: MzI3MjkxMjEyNzI5Njcy
  CLOUDINARY_SECRET: OTBDeENncWRKV3ZORmlxSjZJVmRndTNrVm1J
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljR0YyYVhSb2NtRXhJaXdpWVNJNkltTnRiRFUxY1hWamN6QXdPV2d6WkhOamFtaGpaWFl3YlhjaWZRLlhlUnR1bnY5cDBHeDdHQk5Ia3haeGc=
  DB_URL: bW9uZ29kYitzcnY6Ly9wYXZpdGhyYW1hbmNoYWFtbWFfZGJfdXNlcjpmOTB2YW5LOGFLdDh5c0xOQGNsdXN0ZXIwLnJlbHZxazcubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjA=
  SECRET: cGF2aXRocmE=
